nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.1.cjs

npmScopes:
  fishjam-cloud:
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN-fallback}