openapi: 3.0.0
info:
  title: Room manager
  version: 0.1.0
components:
  schemas: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: Default Response
  /api/rooms:
    get:
      operationId: getToken
      tags:
        - room
      parameters:
        - schema:
            type: string
          in: query
          name: roomName
          required: true
        - schema:
            type: string
          in: query
          name: peerName
          required: true
        - schema:
            type: string
            enum:
              - full_feature
              - audio_only
              - broadcaster
            default: full_feature
          in: query
          name: roomType
          required: false
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  peerToken:
                    type: string
                  url:
                    type: string
                  room:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                  peer:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                required:
                  - peerToken
                  - url
        "410":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  path:
                    type: string
                  method:
                    type: string
                required:
                  - error
        "500":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  path:
                    type: string
                  method:
                    type: string
                  cause:
                    type: string
                required:
                  - error
  /api/rooms/{roomId}/broadcast-viewer-token:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: roomId
          required: true
      responses:
        "200":
          description: Default Response
servers:
  - url: http://localhost:5004
    description: Development server
