name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check formatting
        run: yarn format:check

      - name: Check typing
        run: yarn build:check

      - name: Check docs
        run: yarn docs

  check-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [examples/room-manager]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install SDK
        working-directory: .
        run: yarn --frozen-lockfile

      - name: Check Room Manager example
        working-directory: examples/room-manager
        run: |
          yarn --frozen-lockfile
          yarn build:check
