name: Examples CI

on:
  push:
    branches: [main]
    paths: ['examples/**']

  pull_request:
    branches: [main]
    paths: ['examples/**']

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: [examples/room-manager]

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install SDK
        working-directory: .
        run: yarn --frozen-lockfile

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Check typing
        run: yarn build:check
