name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish-js-sdk:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: yarn
      - run: yarn build
      - run: npm publish
        working-directory: packages/js-server-sdk
