name: Publish Package to npmjs
on:
  push:
    branches: [fix-release-workflow]
  release:
    types: [published]
jobs:
   publish-js-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn npm dist-tag rm @fishjam-cloud/js-server-sdk dev
        working-directory: packages/js-server-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn npm dist-tag add @fishjam-cloud/js-server-sdk latest
        working-directory: packages/js-server-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
